# ==================================================
# Jekyll Configuration for CHARTED Website
# Using Minimal Mistakes Theme + Events Collection
# ==================================================

# Site settings
title: dRTP Skills
logo: /assets/images/drtp-skills-logo.png
description: >-
  Research Technical Professionals (RTPs) are an integral part of the modern process of scientific discovery. The goal of this website is to facilitate the process of discovery and development of digital research technical skills. 

# Theme + skin
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: blue-theme  

show_last_updated_at: false

# Search
search: true

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 5
paginate_path: /page:num/
timezone: # e.g., Europe/London
future: true # Include future-dated posts


# Include folders
include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


defaults:
  # Posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false

  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false

  # Events (collection)
  - scope:
      path: ""
      type: events
    values:
      layout: single
      author_profile: false

collections:
  events:
    output: true
    permalink: /:collection/:name/

# ==================================================
# Archives
# ==================================================

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/